import path from 'path'
import esbuild from 'esbuild'
import process from 'process'
import builtins from 'builtin-modules'
import inlineWorkerPlugin from "esbuild-plugin-inline-worker";
const nodeBuiltins = [...builtins, ...builtins.map((mod) => `node:${mod}`)]

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	plugins: [
		inlineWorkerPlugin({
			define: {
				'process': '{}', // 继承主配置
			},
		}),
		// 添加模块替换插件
		{
			name: 'mobile-compatibility',
			setup(build) {
				// 替换 Node.js 模块为空实现
				build.onResolve({ filter: /^(fs|path|os|crypto|util|stream|events|buffer|url|querystring|assert|readline|child_process|https?|zlib|net|dns|tls|vm|cluster)$/ }, () => {
					return { path: 'mobile-stub', namespace: 'mobile-stub' }
				})
				
				build.onLoad({ filter: /.*/, namespace: 'mobile-stub' }, () => {
					return {
						contents: 'module.exports = {}',
						loader: 'js'
					}
				})
			}
		}
	],
	external: [
		'fs',
		'obsidian',
		'electron',
		'path',
		'moment',
		'child_process',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		'@lexical/clipboard/clipboard',
		// 移动端不支持的模块
		'chokidar',
		'shell-env',
		// 进程相关模块
		'cross-spawn',
		'which',
		'isexe',
		// 其他 Node.js 专用模块
		'util',
		'stream',
		'crypto',
		'os',
		'events',
		'buffer',
		'url',
		'querystring',
		'assert',
		'readline',
		// Git 和版本控制相关
		'simple-git',
		// AI SDK 可能使用的包
		'@modelcontextprotocol/sdk',
		// Node.js 环境检测包
		'isomorphic-ws',
		'ws',
		// 更多可能导致问题的包
		'node-fetch',
		'http',
		'https',
		'zlib',
		'tty',
		'net',
		'dns',
		'timers',
		'worker_threads',
		'v8',
		'vm',
		'perf_hooks',
		'inspector',
		'cluster',
		'dgram',
		'tls',
		'repl',
		'punycode',
		'domain',
		'constants',
		'_http_agent',
		'_http_client',
		'_http_common',
		'_http_incoming',
		'_http_outgoing',
		'_http_server',
		'_stream_duplex',
		'_stream_passthrough',
		'_stream_readable',
		'_stream_transform',
		'_stream_writable',
		'_tls_common',
		'_tls_wrap',
		...nodeBuiltins,
	],
	format: 'cjs',
	define: {
		'import.meta.url': 'import_meta_url',
		// 更全面的环境变量定义
		'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
		'process.env.BROWSER': 'true',
		'process.platform': '"browser"',
		'process.version': '"v16.0.0"',
		'process.versions': '{}',
		'process.arch': '"unknown"',
		'global': 'globalThis',
		'Buffer': 'undefined',
		'__dirname': '"/"',
		'__filename': '"/index.js"',
	},
	inject: [path.resolve('import-meta-url-shim.js')],
	target: 'es2020',
	logLevel: 'info', // 'debug' for more detailed output
	logOverride: {
		'import-is-undefined': 'silent', // 忽略 import-is-undefined 警告
	},
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
})

if (prod) {
	await context.rebuild()
	process.exit(0)
} else {
	await context.watch()
}
