name: Release Obsidian plugin

on:
  push:
    tags:
      - '*'

env:
  PLUGIN_NAME: obsidian-infio-copilot

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Build
        id: build
        run: |
          npm install
          npm run build

      - name: Test
        id: test
        run: |
          npm run test

      - name: Bundle
        id: bundle
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}-${TAG_NAME}.zip ${{ env.PLUGIN_NAME }}
          ls

      - name: Get release notes
        id: release_notes
        run: |
          CHANGELOG=$(sed -n -e "/## ${{ steps.bundle.outputs.tag_name }}/,/---/p" CHANGELOG.md | sed '1d;$d')
          if [ -z "$CHANGELOG" ]; then  
            echo "Error: No release notes found for this version in CHANGELOG.md"  
            exit 1  
          fi  
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ github.token }}
          files: |
            ${{ env.PLUGIN_NAME }}-${{ steps.bundle.outputs.tag_name }}.zip
            main.js
            manifest.json
            styles.css
          body: ${{ steps.release_notes.outputs.body }}
